import Head from "next/head";
import SideBar from "@/components/SideBar";
import Feed from "@/components/Feed";
import RightSideBar from "@/components/RightSideBar";
import { Toaster } from "react-hot-toast";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex ">
        <SideBar />
        <Feed />
        <RightSideBar />
        <Toaster />
      </div>
    </>
  );
}
